services:
  db:
    image: postgres:16-alpine
    container_name: mini_avito_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      # Прокидываем папку с инициализационными скриптами
      - ./deployment/db/init:/docker-entrypoint-initdb.d
      # Изолированный volume для сохранения данных при перезапуске контейнера
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      # pg_isready проверяет, готова ли база принимать подключения
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: